
#Remove hunger and get back to the Beta 1.7.3 days
["No Hunger"]
	#If true, Hunger effect is replaced by Weakness
	"Convert Hunger to Weakness" = true
	#If true, Saturation effect is replaced by Haste
	"Convert Saturation to Haste" = true
	#Make cakes restore 30% missing health, min 1 health
	"Buff cakes" = true
	#(Client Only) If enabled, Foods will show "Snack" when the food instantly heals and "Meal" when the food heals over time. If advanced tooltips are enabled, the food will show how much it restores
	"Food tooltip" = true
	#(Client Only) Armor is rendered in the place of Hunger bar
	"Render armor at Hunger" = true

	["No Hunger"."Food Heal"]
		#The formula to calculate the health regenerated overtime when eating food. Leave empty to disable. Variables as hunger, saturation_modifier, effectiveness as numbers and fast_food as boolean can be used. This is evaluated with EvalEx https://ezylang.github.io/EvalEx/concepts/parsing_evaluation.html.
		"Over Time" = "hunger * 1.5"
		#How much HP does food regen each second? Variables as hunger, saturation_modifier, effectiveness as numbers and fast_food as boolean can be used. This is evaluated with EvalEx https://ezylang.github.io/EvalEx/concepts/parsing_evaluation.html
		"Over time Strength" = "MAX(0.35, 1 / effectiveness * 5)"
		#Over Time Heal will be consumed at the rate of exhaustion multiplied by this
		#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
		"Over time Decay" = 0.01
		#The formula to calculate the health restored instantly when eating. Leave empty to disable. To have the same effect as pre-Beta 1.8 food just use "hunger". Variables as hunger, saturation_modifier, effectiveness as numbers and fast_food as boolean can be used. This is evaluated with EvalEx https://ezylang.github.io/EvalEx/concepts/parsing_evaluation.html.
		"Instant Heal" = "hunger"
		#Foods below this saturation will instantly heal, foods equal or above this threshold will have overtime heal.
		#Range: 0.0 ~ 1.7976931348623157E308
		"Saturation threshold" = 4.0

	["No Hunger".TConstruct]
		#How much health (each level) of the tasty modifier heals
		#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
		"Tasty Health Regen" = 0.25

