
["VMH Entities"]
	#
	#Determines what entities have their size modified by this mod, as well as their min, max, and median sizes.
	#
	#**MUST BE IN THE SAME SPOT AS THE NORMAL 'VMH Entities' ARRAY WHERE VALUES ARE SET.**
	#
	#**Values must be set as follow: 'minecraft/modId:name;vmhSizeMin;vmhSizeMax;vmhSizeMedian;vmhDistributionType'.**
	#
	#*WARNING: Extreme values can cause issues and lag.*
	#
	vmhEntities = ["minecraft:zombie;0.9;1.1;1;0"]

["VMH Entities Whitelist"]
	#
	#Determines what entities have their size modified by this mod.
	#
	#**MUST BE IN THE SAME SPOT AS THE NORMAL 'VMH Entities' ARRAY WHERE VALUES ARE SET.**
	#
	vmhEntitiesWhitelist = ["minecraft:spider"]

["VMH Entities Blacklist"]
	#
	#Determines what entities are blacklist to be used by this mod.
	#
	vmhEntitiesBlacklist = ["minecraft:ender_dragon"]

["Default Spawn Size/Distribution Values"]
	#
	#Determines the default min, max, and median size values a mob can be.
	#
	#The median value sets where the middle of the distribution is set.
	#
	#**Default values: Min=0.8, Max=1,2, Median=1, Distribution=0. Default values will only be used if an entity does not have them set in the config.**
	#
	#**More info on distributions can be found on the mod's page on curseforge.**
	#
	#*WARNING: Extreme values can cause issues and lag.*
	#
	#Range: 0.1 ~ 5.0
	vmhSizeMax = 1.1
	#Range: 0.1 ~ 5.0
	vmhSizeMin = 0.8
	#Range: 0.1 ~ 5.0
	vmhSizeMedian = 1.0
	#
	#Determines the type of distribution to use on entities.
	#
	#Range: 0 ~ 4
	vmhDistributionType = 0

["Buff Health"]
	#
	#Determines whether or not to buff/debuff entity health by their size value.
	#
	vmhBuffHealth = false

["Buff Speed"]
	#
	#Determines whether or not to buff/debuff entity movement/flying speed by their size value.
	#
	vmhBuffSpeed = false

["Buff Attack Damage"]
	#
	#Determines whether or not to buff/debuff entity attack damage by their size value.
	#
	vmhBuffAttackDamage = false

["Buff Attack Speed"]
	#
	#Determines whether or not to buff/debuff entity attack speed by their size value.
	#
	vmhBuffAttackSpeed = false

["Buff Attack Knockback"]
	#
	#Determines whether or not to buff/debuff entity knockback by their size value.
	#
	vmhBuffKnockback = false

["Buff Defense"]
	#
	#Determines whether or not to buff/debuff entity defense by their size value.
	#
	vmhBuffDefense = false

["Modify Jump/Step Height"]
	#
	#Determines whether or not to modify entity jump height/step height by their size value.
	#
	#WARNING: Be careful turning this on, it can cause mobs to have serious issues. It depends on the heights.
	#
	vmhBuffJumpHeight = false

["Do Auto-Compatibility"]
	#
	#Enables/disables auto-compatibility with mobs/creatures.
	#
	vmhDoAutoCompat = true

